.Dd Nov 2, 2016
.Dt SHOWIP 1
.Os
.Sh NAME
.Nm showip
.Nd Simple domain name resolution tool.
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl v
.Ar hostname
.Sh DESCRIPTION
.Nm
Perform DNS lookups through your system's resolver.
.Pp
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h
Show help string.
.It Fl v
Show version.
.El
.Sh EXAMPLE
 $ showip duckduckgo.com
 54.229.105.203
 176.34.155.20
 54.229.105.92
 176.34.135.167
 176.34.131.233
 54.229.105.151
 46.51.197.89

 $ echo kernel.org | showip
 199.204.44.194
 198.145.20.140
 149.20.4.69
 2620:3:c000:a:0:1991:8:25
 2001:4f8:1:10:0:1991:8:25
