.Dd Nov 2, 2016
.Dt SHOWIP 1
.Os
.Sh NAME
.Nm showip
.Nd Simple domain name resolution tool.
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl v
.Ar hostname
.Sh DESCRIPTION
.Nm
Perform DNS lookups through your system's resolver.
.Pp
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h
Show help string.
.It Fl v
Show version.
.El
.Sh EXAMPLE
 $ showip duckduckgo.com
 duckduckgo.com: /ipv4/54.229.105.203
 duckduckgo.com: /ipv4/176.34.155.20
 duckduckgo.com: /ipv4/54.229.105.92
 duckduckgo.com: /ipv4/176.34.135.167
 duckduckgo.com: /ipv4/176.34.131.233
 duckduckgo.com: /ipv4/54.229.105.151
 duckduckgo.com: /ipv4/46.51.197.89

 $ echo kernel.org | showip
 kernel.org: /ipv4/199.204.44.194
 kernel.org: /ipv4/198.145.20.140
 kernel.org: /ipv4/149.20.4.69
 kernel.org: /ipv6/2620:3:c000:a:0:1991:8:25
 kernel.org: /ipv6/2001:4f8:1:10:0:1991:8:25
